---
title: "dataset_generation"
output: html_document
date: "2026-02-24"
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
source("../src/preprocessing.R")
source("../src/plot.R")
source("../src/grid_thinning.R")
```
```{r}
shp_path <- "../../data/shp/argentina/argentina.shp"
```

## Dataset generation pipeline

```{r}
df_trametes_sanguinea <- read_csv("../../data/ocurrences/raw/df_trametes_sanguinea.csv")
plot_points_in_map(df_trametes_sanguinea, "../../data/shp/argentina/argentina.shp")
```


### Preprocesamiento

#### Filtros de calidad


```{r, warning=FALSE}
  df_path <- "../../data/ocurrences/raw/df_trametes_sanguinea.csv"
  preproc_path <- "../../data/ocurrences/processed/df_trametes_sanguinea.csv"
  min_year <- 1945
  scientific_name <- 'Polyporaceae'
  max_uncertainty_km <- 10
  tests <- c(#"capitals",
              #"centroids",
              "equal",
              "duplicates",
              #"gbif",
              #"institutions",
              "outliers",
              #"seas",
              "zeros"
              #"urban"
              )
  
  preproc <- preprocess_dataset(df_path,
                                preproc_path,
                                min_year,
                                scientific_name,
                                max_uncertainty_km,
                                shp_path,
                                tests)
  
  df_clean <- preproc$df_clean
  df_flagged <- preproc$df_flagged
  
  plot_points_in_map(df_clean, shp_path)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}

out_dir. <- "../../data/ocurrences/processed"

res <- grid_thin_gbif(
  df = df_clean,
  grid_sizes_km = c(10, 25, 50),
  out_dir = "outputs/thinning",
  prefix = "trametes_sanguinea",
  seed = 42
)

res$summary
```
```{r}
plot_points_in_map(res$thinned_df$grid_10km, shp_path)

```

